### ISSUE TITLE
Win support for Meteor 0.6.5

### ISSUE THREAD

**Issue by shirajdesilva** [sdarnell/meteor-win#15]
Inquiring as to when you are likely to have windows support for Meteor 0.6.5. Thanks.

**Comment by sdarnell** [comment]
I'm working on it now - but as you may be aware the 0.6.5 release was a massive change from 0.6.4.1.

Current status is that it runs most of the examples locally. But word play doesn't work quite right.

Deploy is the other major limitation.

**Comment by sdarnell** [comment]
I've just released 0.6.5 see https://github.com/sdarnell/meteor/wiki/Windows
