### ISSUE TITLE
Form tag issue

### ISSUE THREAD

**Issue by SoumenDas** [sdarnell/meteor-win#21]
Form tag in one template blocks other template from rendering.
Using meteor 0.6.4.1 in windows 8 & 7. I didn't check in ubuntu.

To reproduce:
1. git clone https://github.com/SoumenDas/meteor_form_bug.git
2. click the next button
3. If form tag in template part1 is commented then everything works fine.

**Comment by sdarnell** [comment]
I had a quick look and it isn't obvious what the issue is, but I'm certain it isn't anything windows specific, so the core meteor repository is the best place to raise the issue.

I would also suggest cutting the part1 template down a bit until it works.
