### ISSUE TITLE
Console errors have funny characters around the date/time

### ISSUE THREAD

**Issue by sdarnell** [sdarnell/meteor-win#24]
When you get errors on the meteor console, the date/time has funny chars at the start and end:

```
I20140109-08:54:13.655(0)?
```

I suspect this is due to the escape sequences used to colour the text.

**Comment by sdarnell** [comment]
I also need to check whether the `(0)` is deliberate or part of the control sequences.

**Comment by k5e** [comment]
While you're at it, Stephen, the dark blue colour of the datetime part is hardly visible on the black console window background.

**Comment by sdarnell** [comment]
FWIW: There is a command line option --raw-logs which disables the coloring and addition of the date/time.

The date/time formatting seems to be done by packages/logging.js
and the (0) is the timezone (e.g. 0 = GMT/UTC in my case).
I'm a little surprised ISO8601 wasn't used.

Coloring is done by npm cli-color (https://npmjs.org/package/cli-color), but that doesn't seem to be at fault.

**Comment by sdarnell** [comment]
Finally, it turns out that the W or I at the beginning is the 'type' of the message (presumably W=Warning or I=Info). The question mark indicates that the time is 'inexact'. Not sure why this is so critical or what constitutes 'exact' but it seems to be behaving the same as non-windows.

As for the dark blue color, I have changed that to Cyan.  See commit dbea081fa7ac2d4eab37ca535b04597137d5bf37

**Comment by k5e** [comment]
Thanks Stephen, for shedding light on the "extra characters" and for the color change.
