### ISSUE TITLE
Crash in mongo_runner.js on project start

### ISSUE THREAD

**Issue by webmaxru** [sdarnell/meteor-win#25]
I use Windows7 x64 system with administrator rights. I set up Meteor and created a new project called test2. Right after start of it I receive an error message. Here is full log of my actions after Meteor installation:

```
C:\Users\max\AppData\Local\.meteor>meteor create test2
test2: created.

To run your new app:
   cd test2
   meteor

C:\Users\max\AppData\Local\.meteor>cd test2

C:\Users\max\AppData\Local\.meteor\test2>meteor
[[[[[ C:\Users\max\AppData\Local\.meteor\test2 ]]]]]


C:\Users\max\AppData\Local\.meteor\tools\dc9e17e4f8\tools\mongo_runner.js:371
    }).run();
       ^
[object Object]
```

Does it mean I need to install any extra software (MongoDB) to run Meteor server?

**Comment by sdarnell** [comment]
First off, I notice that you are creating projects in the %LOCALAPPDATA%.meteor directory. That is not expected, and not where you should be creating projects. That .meteor directory is for meteor application's use.

However, having said that I can't think why that would be causing the issue you are seeing.

I use Win7 x64 and don't see this issue. Here's what I see:

```
c:\meteor>meteor create test2
test2: created.

To run your new app:
   cd test2
   meteor

c:\meteor>cd test2

c:\meteor\test2>meteor
[[[[[ c:\meteor\test2 ]]]]]

Initializing mongo database... this may take a moment.
=> Meteor server running on: http://localhost:3000/
```

Meteor is intended to be self contained, so you shouldn't need to install mongodb or nodejs. In fact the more likely situation is that if you have versions of these installed that they may be interfering with Meteor. Please check your PATH variable and look for NODE_xxx like environment variables.

I also have assumed that you are using version 0.7.0.1, but please could you confirm.

**Comment by sdarnell** [comment]
Hopefully the previous comments helped resolve the issue - we can re-open if not.
