### ISSUE TITLE
Mongodb Cannot start

### ISSUE THREAD

**Issue by Kulikovpavel** [sdarnell/meteor-win#26]
After install with lastest "LaunchMeteor.exe" i create app and try to run it, but get this error

C:!!!!WORK\Сайты\meteor\geoDataMO>meteor
[[[[[ C:!!!!WORK\Сайты\meteor\geoDataMO ]]]]]

Unexpected mongo exit code 100. Restarting.

Unexpected mongo exit code 100. Restarting.

Unexpected mongo exit code 100. Restarting.

Can't start mongod

MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.

meteor reset didnt work, delete lock file too.

EDIT:
Found error, it is cyrillic chars in path.
With english only all work fine.

**Comment by sdarnell** [comment]
OK, glad you have a work-around.
Did you establish whether the code that doesn't like the filename is in meteor, node, or mongodb?
Are any changes needed to meteor?
