### ISSUE TITLE
Force-ssl does not count ::1 as a local address

### ISSUE THREAD

**Issue by yeputons** [sdarnell/meteor-win#28]
On my system (Windows 7, which supports IPv6) default outgoing address is `::1` (IPv6's equivalent of `127.0.0.1`). Therefore, in `force-ssl/force-ssl-server.js:18` the `remoteAddress` variable has `127.0.0.1`, but `x-forwarded-for` is `::1`, which is, obviously, not equal to `127.0.0.1`.

This leads to force redirection to https in development environment even without a port (just to `https://localhost/`), which is not listened by anyone.

Not sure if it's Windows-only bug, because Linux supports IPv6 as well.

**Comment by yeputons** [comment]
@sdarnell Thank you: meteor/meteor#1751 .

Are you going to update `LaunchMeteor.exe` with this fix one day?

**Comment by sdarnell** [comment]
Yes, there are a couple of issues that mean I need to re-release. I was hoping to do it this weekend, but it should be soon anyway.

Once again, thanks for preparing the change and also raising the upstream issue,
