### ISSUE TITLE
use the Latest Meteor for Windows (exe bootstrapper) to install and got a error

### ISSUE THREAD

**Issue by tounaer** [sdarnell/meteor-win#34]
I use Latest Meteor for Windows (exe bootstrapper) to install meteor on my windows 7(32 bit os)，and after download files to setup the program i got a error  as follows:

Downloading initial Meteor files...
100 ###########################################################################
Download complete (33.7 MB)
Extracting files to C:\Users{user}\AppData\Local.meteor
................................................................................
....
Error processing path: C:\Users....\AppData\Local.meteor~\packages\less\8
236d0d585\plugin.compileLess.os\npm\compileLess\plugin\node_modules\less\node_mo
dules\request\node_modules\form-data\node_modules\combined-stream\node_modules\d
elayed-stream\test\integration\test-delayed-http-upload.js
Deleting directory: C:\Users\zhenggang\AppData\Local.meteor~
Unexpected exception: System.IO.PathTooLongException: 

   在 System.IO.Path.SafeSetStackPointerValue(Char\* buffer, Int32 index, Char va
lue)
   在 System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
   在 System.IO.Path.NormalizePath(String path, Boolean fullCheck)
   在 System.IO.Path.GetDirectoryName(String path)
   在 LaunchMeteor.Program.ExtractTgz(Stream stream, String directory, Func`2 tr
ansform)
   在 LaunchMeteor.Program.BootstrapWarehouse(String warehouse)
   在 LaunchMeteor.Program.Main(String[] args)

anybody who knows how to solve it?

**Comment by sdarnell** [comment]
Hi @tounaer, the latest version of meteor needs really long filenames and the standard .Net code refuses to handle them. So I had to modify LaunchMeteor.exe to use the underlying Win32 APIs that allow a bit more control.

The latest version on http://win-install.meteor.com/LaunchMeteor.exe has been updated, and you will need to use that version to install the latest versions.  From the stack trace I can see that you are not using the latest.

The latest will have a file/product version number of 0.3.1.0 when you look at the file properties with Windows explorer. For example:
![image](https://f.cloud.github.com/assets/3684334/2343302/addfd9ac-a50c-11e3-9abc-2281aca8339a.png)

So, please download LaunchMeteor.exe again and have another go.

**Comment by sdarnell** [comment]
Did that resolve the problem?

**Comment by sdarnell** [comment]
Closing issue, but please re-open if there is still an problem.
