### ISSUE TITLE
Can't login and logout with MinimongoError (0.7.1.2 / winXP)

### ISSUE THREAD

**Issue by ChJJin** [sdarnell/meteor-win#37]
After running Meteor with release 0.7.1.2 on Windows XP,  
I couldn't login in a browser window with the following error came out

```
Uncaught MinimongoError: cant' set field named $push
```

and couldn't logout as well ( login before )

```
Uncaught MinimongoError: cant' set field named $pull
```

but it works well on Linux (0.7.1.2) as development.

**Comment by sdarnell** [comment]
Modern MongoDB (2.4.9) doesn't support WInodows XP, so I include an older version of mongodb specifically to support WinXP (mongodb 2.0.9). My guess is that there is either a bug or limitation of this version of mongodb.

There are quite a few uses of $push (and less of $pulll).

The thing I don't quite understand is why minimongo is giving the error (client side).
Please could you give more stack trace information, and ideally run:
   meteor test-packages

And connect your browser to localhost:3000. This should run a suite of tests including minimongo ones.

**Comment by ChJJin** [comment]
@sdarnell 
There were no errors about minimongo when I used Meteor with release 0.6.4 before.
And I guess that some inner functions of Meteor or Account packages might be upgraded which is using the interface of modern MongoDB. Then I tried to use the earlier version of some packages, but it didn't work yet. 
Now I have no idea to fix it . 

Here is the detail of the error.

```
Uncaught MinimongoError: can't set field named $push minimongo.js:93
MinimongoError minimongo.js:93
findModTarget minimongo.js:2837
(anonymous function) minimongo.js:2741
_.each._.forEach underscore.js:164
(anonymous function) minimongo.js:2728
_.each._.forEach underscore.js:164
LocalCollection._modify minimongo.js:2721
LocalCollection._modifyAndNotify minimongo.js:798
(anonymous function) minimongo.js:715
LocalCollection._eachPossiblyMatchingDoc minimongo.js:602
LocalCollection.update minimongo.js:710
self._connection.registerStore.update mongo-livedata.js:237
store.(anonymous function) livedata.js:3557
(anonymous function) livedata.js:4184
_.each._.forEach underscore.js:156
(anonymous function) livedata.js:4183
_.each._.forEach underscore.js:164
_.extend._livedata_data livedata.js:4180
onMessage livedata.js:3372
(anonymous function) livedata.js:2705
_.each._.forEach underscore.js:156
self.socket.onmessage livedata.js:2704
REventTarget.dispatchEvent livedata.js:150
SockJS._dispatchMessage livedata.js:1135
SockJS._didMessage livedata.js:1193
that.ws.onmessage
```

**Comment by ChJJin** [comment]
@sdarnell I get what you mean now. 
what about cover the files about minimongo with the earlier version ones ?

**Comment by sdarnell** [comment]
There have been quite extensive changes to minimongo support in the recent Meteor releases, so I guess that something there may have changed. However, I would have expected those to have failed on Win7 as well.

The other thing which is worth checking given you said version 0.6.4, is that the previous versions have definitely been uninstalled, and having two copies of meteor on your PATH can cause issues.

Note that in the current 0.7.2 minimono.js (both before processing and after) seems to have different code at line 93.

The exception "can't set field named ..." is in modify.js at line 153, and after processing at line 3121 of minimongo.js.

Looking further back for markers, there is a call to _eachPossiblyMatchingDoc() around the 600 mark, and it does call an anonymous function, But the call of _eachPossiblyMatchingDoc() that includes a call to _modifyAndNotify() at line 677 (processed 685).

Now minimongo may have changed between 0.7.1.2 and 0.7.2, but I'm not sure they're matching up.

So, please could you:
- Check previous versions of meteor are uninstalled from control panel add/remove programs
- Upgrade to 0.7.2 and try again
- Confirm which authentication mechanism (email+password, google, facebook, github etc.) authentication provider you are using.

Thanks,
 Stephen

**Comment by sdarnell** [comment]
Ah, I almost forgot, please can you also check whether you have a node.exe in your path, or any environment variables starting NODE, the following commands should do that:

```
   where node.exe
   set NODE
```

**Comment by sdarnell** [comment]
Please re-open the issue if you still have issues.
