### ISSUE TITLE
Meteor v0.8

### ISSUE THREAD

**Issue by piffie** [sdarnell/meteor-win#38]
Hi,

Just want to check when do you think a support will be available. Because we need to wait for this, and would like to plan when we make the switch. Just a rough timeline would be great.

Keep up the great work!
Cheers

**Comment by sdarnell** [comment]
Should be complete and released today (Saturday)

**Comment by rynti** [comment]
Very glad to hear that, looking forward to playing with 0.8 on Windows :+1:

**Comment by sdarnell** [comment]
0.8.0 is now available on an internet near you :)
