### ISSUE TITLE
Install freeze (LaunchMeteor.exe)

### ISSUE THREAD

**Issue by jda0** [sdarnell/meteor-win#39]
Downloading initial meteor files freezes at a random value each time, whether it be 05, 33, 49... Numberwang. This is consistent in its existence and randomness.

Win 7 64-bit
Node 10.26

**Comment by sdarnell** [comment]
When did this start happening? How long did you leave it?
Note that I have just released a new version and there may be a higher than usual demand on the servers. You may need to be a little patient.

Did you get any error at all, or just a hang?

**Comment by jda0** [comment]
Tried twice today, ~1 hour hang (no error) each time. I'll try again tomorrow!

**Comment by sdarnell** [comment]
If really necessary, you can download the initial package manually from: `https://win-install.meteor.com/bootstrap/meteor-bootstrap-Windows_i686.tar.gz`

And place it in the same directory as LaunchMeteor.exe and then invoke:

```
LaunchMeteor.exe -downloaded
```

Looking at the logs, in the past 20mins or so, there were 4 downloads of the bootstrap package, though two were from the same IP. No obvious errors.

**Comment by sdarnell** [comment]
Please re-open if you still have issues.
