### ISSUE TITLE
Could not install on Windows Server 2008 R2

### ISSUE THREAD

**Issue by maxpain** [sdarnell/meteor-win#44]
![2014-07-10 19-50-19 dota 560 693 044](https://cloud.githubusercontent.com/assets/5875582/3538510/ca47228a-0830-11e4-8cce-36fbce8facc3.png)

**Comment by maxpain** [comment]
oops. Net framework.. i just forgot install this...

**Comment by sdarnell** [comment]
Yeah the build shouldn't rely on .net 3.5, but I'm afraid it does for now.
