### ISSUE TITLE
Cannot upgrade to Meteor 0.8.3

### ISSUE THREAD

**Issue by steph643** [sdarnell/meteor-win#47]
Previously I had no problem updating my projects to the latest Meteor version using "meteor update".
But now it seems Meteor 0.8.3 is available and "meteor update" says that 0.8.2 is the latest version.
Do you have the same issue? Is it related to the Windows port?

**Comment by sdarnell** [comment]
I haven't released 0.8.3 yet. Thought I have been working on it.
It should be available in the next few minutes.

**Comment by sdarnell** [comment]
0.8.3 has been released and seems to be working fine.

**Comment by steph643** [comment]
It is working fine, indeed. Thanks a lot!
