### ISSUE TITLE
Packages: Package undefined

### ISSUE THREAD

**Issue by productiveme** [sdarnell/meteor-win#5]
When trying to run a meteor app with a "packages" folder containing a package such as accounts-asana, a reference error: Package is not defined is thrown from the package.js file line 1. This doesn't occur on Mac OS.

**Comment by sdarnell** [comment]
Which version of meteor are you using on linux and windows?
What is the exact stack trace?
Can you share simple repro steps or example?

I gave it a quick try with accounts-asana using the following steps:
1. create an example with auth (`meteor create --example parties`)
2. Download an extract accounts-asana to parties\packages (renaming the directory to just 'accounts-asana')
3. Run meteor.

The resulting bundle seems to have correctly handled the package (look in `parties\.meteor\local\build\app\packages\accounts-asana`).

I don't get any problem with the reference to 'Package', and it looks to me that the package.js has been correctly read as `meteor list` displays it and its description.

Instead I get an error referencing Template from asana_configure.js:

```
ReferenceError: Template is not defined
    at app/packages/accounts-asana/asana_configure.js:1:16
    at c:\meteor\parties\.meteor\local\build\server\server.js:294:12
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Program Files (x86)\Meteor\lib\node_modules\underscore\underscore.js:79:11)
    at run (c:\meteor\parties\.meteor\local\build\server\server.js:227:7)
=> Exited with code: 1
```

The caller at server.js:294 is the caller that wraps the code in a function(Npm) {...}

However, I don't see why the accounts-asana is any different to the other packages in the .meteor/local/build/app/packages/... directory.

**Comment by sdarnell** [comment]
I'm pretty sure I've managed to fix the problem in 0.6.3.1-rev3 - please give it a try and let me know how you get on. I was able to get the option for logging in with asana on the parties example.

**Comment by sdarnell** [comment]
Sorry, didn't mean to close the issue before getting a response.

**Comment by productiveme** [comment]
My apologies for misleading you with the error, I got the Template not defined first, then wrapped that with a test for Template and then got the Package not defined. I assumed that would be the root of the problem and that it would apply to all packages.

I tried with 06.3.1-rev3 now and all seems to work as it should.
<3
