### ISSUE TITLE
Couldn't find git.exe on PATH

### ISSUE THREAD

**Issue by peterennis** [sdarnell/meteor-win#53]
Test building 0.9.0.1 from HowToBuild.md

C:\ae\meteor>scripts\windows\build.bat
...
C:\ae\meteor>if errorlevel 1 (
echo Couldn't find git.exe on PATH
 popd
 goto:eof
)
Couldn't find git.exe on PATH

C:\ae\meteor>

I installed Git-1.9.4-preview20140815.exe
Default selection is not to change the path. My guess is that
causes the error.
I will try again and allow the path change.

**Comment by sdarnell** [comment]
There are lots of ways to get GIT on your system, and the executables get stored in different places. So the only viable route is to require you to have git.exe on your PATH.

Note however, that 0.9.0.1 branch is not working yet, so I fear you will be wasting your time.
Meteor core has changed enough that the process for building a release will need to change.
If you are desperate to build from source then the 0.8.3 branch is your best bet, but if you want 0.9.x you will have to wait or go through a lot of pain, and I'm not going to be able to help you until I've finished.

**Comment by peterennis** [comment]
Reinstalled git with path change.
See below Error: ENOENT ...

C:\ae\meteor>if [win0.9.0.1] == [](echo Skipping bootstrap package as release n
ame not specified)  else (
echo Building bootstrap package
 dev_bundle\bin\node.exe scripts\admin\build-bootstrap.js win0.9.0.1
 echo Copying LaunchMeteor.exe
 copy scripts\windows\LaunchMeteor.exe dist\public
)
Building bootstrap package
Error:  { [Error: ENOENT, no such file or directory 'C:\ae\meteor\dist\release.j
son']
  errno: 34,
  code: 'ENOENT',
  path: 'C:\ae\meteor\dist\release.json',
  syscall: 'open' }
Can't read release manifest C:\ae\meteor\dist\release.json
Copying LaunchMeteor.exe
        1 file(s) copied.

C:\ae\meteor>popd

C:\ae\meteor>

Not sure what this error means.

**Comment by peterennis** [comment]
I will try the build again when you are done.
