### ISSUE TITLE
Source maps should probably use forward slashes 

### ISSUE THREAD

**Issue by sdarnell** [sdarnell/meteor-win#56]
After investigating a sourcemap issue, it looks to me like source map consumers (Chrome at least), expect the original filenames to be with forward slashes.

For example if you open up Chrome dev tools and select sources, then look in the packages folder, you will see it seems a little confused.
![image](https://cloud.githubusercontent.com/assets/3684334/4264169/5116269c-3c18-11e4-973f-dadf6f0e8bcb.png)

Luckily it doesn't seem to be a big problem (other than the logging package), so I'm putting this on the back burner for now. 

NB The SourceMap spec doesn't say anything specific on the issue.

![image](https://cloud.githubusercontent.com/assets/3684334/4264177/d310c0a8-3c18-11e4-8435-28d2357ea247.png)

**Comment by sdarnell** [comment]
It also seems impacts stack traces in the browser.

**Comment by aadamsx** [comment]
Any showstoppers for the port to 0.9.x so far?
