### ISSUE TITLE
Meteor stuck at "Starting your app..."

### ISSUE THREAD

**Issue by solcates** [sdarnell/meteor-win#62]
Environment:
- Windows 8.1, 64bit
- Meteor 0.9.0.1-rc3 release (aka - "LaunchMeteor09.exe)"
- Vanilla Project

Description:
I create a new project after installing 0.9.0.1-rc3, and then ran meteor in that project.
Meteor hangs at "Starting your app..."  Have let it run for about an hour, no change in behaviour.
CPU is running at about 20-25% with node.exe so it's doing something, just not progressing.
No errors in Event Viewer that i can see.

Any ideas?

**Comment by solcates** [comment]
Quick update... disabled A/V software, did full uninstall, and reinstall... same behaviour.

**Comment by sdarnell** [comment]
On windows 8 there seems to be an increased risk of issues with fibers. Some people find that setting the following helps.

```
set __COMPAT_LAYER=WIN7RTM
```

The next thing I'd suggest is to insert some trace statements to help identify where the blockage is.
It's not necessarily easy to know where to put them, and unfortunately I'm away from my machine for a little while so I can't help in detail.

The other thing to try is 'meteor reset'. It shouldn't be necessary, but it may help.

**Comment by sdarnell** [comment]
One other thing to try is to create an example, e.g. todos and if necessary trim that down rather than starting from a completely empty project.

**Comment by solcates** [comment]
Thanks Stephen.  I tried setting the environment variable __COMPAT_LAYER and it didn't seem to do much for me.  

I'll try a few examples as well, and come back with anything i discover.

**Comment by dimkk** [comment]
Same issue here, keep digging

**Comment by cedricmiv** [comment]
Same for me. I'm trying to find more informations to better define the problem.

**Comment by cedricmiv** [comment]
I do not know if it will help. If I create a project from an example that does not work. When I run an example of its original directory everything works fine. By cons, if I try to update the original examples, it crashes. 
In any case thank you for your work sdarnell.

Failed to update Meteor.
XXX\AppData\Local.meteor\tools\dc9fb5197a\lib\node_modules\fibers\f
uture.js:173
                                                throw(ex);
                                                      ^
Error: ENOENT, no such file or directory 'XXX\AppData\Local.meteor\
releases\latest'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at fs_readlinkSync (XXX\AppData\Local.meteor\tools\dc9fb5197a\t
ools\warehouse.js:57:15)
    at Object._.extend.latestRelease (XXX\AppData\Local.meteor\tool
s\dc9fb5197a\tools\warehouse.js:128:20)
    at Object._.extend.fetchLatestRelease (XXX\AppData\Local.meteor
\tools\dc9fb5197a\tools\warehouse.js:171:41)
    at main.registerCommand.name [as func](XXXAppDataLocal.meteo
rtoolsdc9fb5197atoolscommands.js:361:17)
    at XXX\AppData\Local.meteor\tools\dc9fb5197a\tools\main.js:974:
23

Please press any key to exit.

**Comment by sdarnell** [comment]
Thanks @Greeench, so to clarify, creating a verbatim example works, but after doing a `meteor update` the same example no longer works?

Looking at the stack trace it looks like it is running a pre-0.9 version and it is trying to update the previous 'warehouse' version.

Please check how you are launching meteor. You need to be executing the meteor.exe from %LOCALAPPDATA%.meteor and this executable should have a version number of 0.4.0.0 if you click properties in explorer.

**Comment by sdarnell** [comment]
It is worth enabling environment variable METEOR_DEBUG_BUILD=1 to see if any useful debugging is produced when it hangs during app startup.

**Comment by cedricmiv** [comment]
Sorry it take like two hours to have the error and i think nothing new. With environment variable METEOR_DEBUG_BUILD=1:

START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
START CAPTURE 1 loading unipackage
END CAPTURE 1 loading unipackage
END CAPTURE 0 undefined
[[[[[ XXX\meteor\test9 ]]]]]

=> Started proxy.
START CAPTURE 0 undefined
START CAPTURE 1 loading unipackage
END CAPTURE 1 loading unipackage
END CAPTURE 0 undefined|
START CAPTURE 0 loading unipackage
END CAPTURE 0 loading unipackage
=> Started MongoDB.
START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
START CAPTURE 0 loading unipackage
END CAPTURE 0 loading unipackage
END CAPTURE 0 undefined
START CAPTURE 0 building the application
START 1 loading plugin `basicFileTypes` from package `meteor`
DONE 1 loading plugin `basicFileTypes` from package `meteor`
START 1 loading plugin `compileTemplates` from package `templating`
DONE 1 loading plugin `compileTemplates` from package `templating`
START CAPTURE 1 loading unipackage
END CAPTURE 1 loading unipackage
START CAPTURE 1 loading unipackage
END CAPTURE 1 loading unipackage
START CAPTURE 1 loading unipackage
END CAPTURE 1 loading unipackage
START CAPTURE 0 loading unipackage
END CAPTURE 0 loading unipackage
END CAPTURE 0 building the application
START CAPTURE 0 preparing to run
END CAPTURE 0 preparing to run
START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
END CAPTURE 0 undefined

!!! loop 1 or 2 hours like this, repeated hundreds of times !!!

START CAPTURE 0 building the application
END CAPTURE 0 building the application
START CAPTURE 0 preparing to run
END CAPTURE 0 preparing to run
START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
END CAPTURE 0 undefined
START CAPTURE 0 undefined
END CAPTURE 0 undefined

!!!

START CAPTURE 0 building the application
rm_recursive got ENOTEMPTY retrying
END CAPTURE 0 building the application

XXX\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27\meteor
-tool-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:173
                                                throw(ex);
                                                      ^
Error: EPERM, operation not permitted 'XXX\meteor\test9.3.meteor\lo
cal.build922007.build\programs\ctl'
    at Object.fs.renameSync (fs.js:548:18)
    at XXX\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27
\meteor-tool-os.windows.x86_32\tools\files.js:664:8
    at Object.files.retryOnEperm (XXX\AppData\Local.meteor\packages
\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\files.js:625:7)
    at Object.files.renameDirAlmostAtomically (XXX\AppData\Local.me
teor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\fil
es.js:663:9)
    at _.extend.complete (XXX\AppData\Local.meteor\packages\windows
_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\builder.js:516:11)
    at writeTargetToPath (XXX\AppData\Local.meteor\packages\windows
_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\bundler.js:1515:11)
    at XXX\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27
\meteor-tool-os.windows.x86_32\tools\bundler.js:1614:26
    at Function._.each._.forEach (XXX\AppData\Local.meteor\packages
\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\dev_bundle\lib\node_mo
dules\underscore\underscore.js:87:22)
    at writeSiteArchive (XXX\AppData\Local.meteor\packages\windows_
meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\bundler.js:1613:7)
    at XXX\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27
\meteor-tool-os.windows.x86_32\tools\bundler.js:1999:20
    at XXX\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27
\meteor-tool-os.windows.x86_32\tools\buildmessage.js:186:11
    at _.extend.withValue (XXX\AppData\Local.meteor\packages\window
s_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\fiber-helpers.js:112:14
)
    at XXX\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27
\meteor-tool-os.windows.x86_32\tools\buildmessage.js:183:27
    at _.extend.withValue (XXX\AppData\Local.meteor\packages\window
s_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\fiber-helpers.js:112:14
)
    at XXX\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27
\meteor-tool-os.windows.x86_32\tools\buildmessage.js:181:16
    at _.extend.withValue (XXX\AppData\Local.meteor\packages\window
s_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\fiber-helpers.js:112:14
)
    at Object.capture (XXX\AppData\Local.meteor\packages\windows_me
teor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\buildmessage.js:172:21)
    at Object.exports.bundle (XXX\AppData\Local.meteor\packages\win
dows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\bundler.js:1714:31)
    at bundleApp (XXX\AppData\Local.meteor\packages\windows_meteor-
tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:469:28)
    at _.extend._runOnce (XXX\AppData\Local.meteor\packages\windows
_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:487:24)
    at _.extend._fiber (XXX\AppData\Local.meteor\packages\windows_m
eteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\run-app.js:670:28)
    at XXX\AppData\Local.meteor\packages\windows_meteor-tool\1.0.27
\meteor-tool-os.windows.x86_32\tools\run-app.js:360:12

Please press any key to exit.

**Comment by lxblink** [comment]
If I set `self.watchForChanges = false` in run-app.js in `_runOnce` function, before setting watchers, app starting.
As I understand, something wrong with watchers.

when checked deeply in watch.js, saw very strange things:

```
c:\github\meteor\packages\underscore\package.js
null
c:\github\meteor\packages\underscore\package.js
null
d:\work\meteor_proj\newapp\no-default-targets
null
C:\Users\X\AppData\Local\.meteor\packages\windows_meteor-tool\1.0.27\meteor-
tool-os.windows.x86_32\dev_bundle\.bundle_version.txt
0.3.49

bdffdb7ccbe411ac29c35883b5f3300d4fac0f10
bdffdb7ccbe411ac29c35883b5f3300d4fac0f10
```

it is my stdout in '_fireIfFileChanged'
`absPath`, `contents` and hashes, if not `return` before

don't understand why there is github on my C: drive) 
I haven't this folder)

maybe it will be helpful.

**Comment by sdarnell** [comment]
@lxblink this is very interesting/promising. As it happens c:\github\meteor is where I build the meteor releases. It looks as if the package bundles have some absolute paths when they should be relative.

This would also explain why I don't have the same problem that others are having. I would expect a more definitive error message rather than retrying forever. From memory I think the file watcher is meant to ignore files that it can't stat.
But underscore is so fundamental in meteor that it may be dying in a horrible way that it can't cleanly recover from.

**Comment by vbezruchkin** [comment]
@sdarnell I have the same issue like described above. Meteor start simply freezes. I tried all possible solutions here - nothing worked. Just to confirm, should we all wait for a solution soon? Thanks

P.S. I have a vagrant copy, anyhow I really think your solution would be a better way if it works properly. thanks btw :)

**Comment by sdarnell** [comment]
I'm currently out of the country unable to access my dev box remotely. But I'll be back home soon and given the information from lxblink I should be able to reproduce the issue. So hopefully I'll be able to fix it in the next few days.

**Comment by sdarnell** [comment]
OK, I have reproduced it locally and have a temporary work-around.
Essentially you need to delete all of the `buildinfo.json` files under `%LOCALAPPDATA%\.meteor`

I used powershell: `dir -rec buildinfo.json | %{ del $_ }` but you could use a DOS for loop, or use explorer to search in the folder for buildinfo.json and the select all and delete.

I'll look at fixing the release properly so that I don't include the buildinfo.json files.

By the way, even with the work-around, you will notice that it is still painfully slow to start. Subsequent builds of meteor should improve this.

**Comment by peterennis** [comment]
Win 8.1 x32
Meteor 0.9.0.1-rc3
I can confirm the startup app works for IE11 and Chrome 38 when all buildinfo.json files are deleted.
@sdarnell Thanks!

**Comment by vbezruchkin** [comment]
@sdarnell thanks for the hotfix. Now it's working fine!

I use total commander, I found all buildinfo.json file in the folder and deleted all of them. It took a bit longer to start but my meteor started. Thanks a lot again. Cheers from Kyrgyzstan :)

**Comment by sdarnell** [comment]
I've updated the bootstrap package to no longer include the buildinfo.json files, and uploaded that tarball so that subsequent installs won't have the issue. Once again, thanks to @lxblink for the crucial pointer in the right direction.

**Comment by cedricmiv** [comment]
Thx you for your amazing work
