### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by kgeo** [sdarnell/meteor-win#63]
I am unable to install from LaunchMeteor.exe. On XP SP3 I get this output with subsequent error:

```
Downloading initial Meteor files...
100 ###########################################################################
Download complete (37 MB)
Extracting files to C:\Documents and Settings\user1\Application Data\.meteor
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
...........................................................
Extracted 7347 files (126,5 MB)
Files extracted successfully

Updating PATH to include C:\Documents and Settings\user1\Application Data\.meteo
r

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: no errorC:\Documents and Settings\user1\Application Data\.meteor\tools\dc
9fb5197a\lib\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Documents and Settings\user1\Application Data\.met
eor\tools\dc9fb5197a\lib\node_modules\fibers\fibers.js:17:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Please press any key to exit.
```

**Comment by peterennis** [comment]
@kgeo - Thanks for the report but as Microsoft no longer supports XP and (officially) Meteor

does not actually support Windows yet my recommendation is to try with Windows 7

as the minimum.

The bug report may help @sdarnell in some way with current development

but I do not understand enough to make that call.

```
  On Thursday, November 6, 2014 3:26 AM, kgeo <notifications@github.com> wrote:
```

I am unable to install from LaunchMeteor.exe. On XP SP3 I get this output with subsequent error:
Downloading initial Meteor files...
100 ###########################################################################
Download complete (37 MB)
Extracting files to C:\Documents and Settings\user1\Application Data.meteor
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
...........................................................
Extracted 7347 files (126,5 MB)
Files extracted successfully

Updating PATH to include C:\Documents and Settings\user1\Application Data.meteo
r

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: no errorC:\Documents and Settings\user1\Application Data.meteor\tools\dc
9fb5197a\lib\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Documents and Settings\user1\Application Data.met
eor\tools\dc9fb5197a\lib\node_modules\fibers\fibers.js:17:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Please press any key to exit.

**Comment by sdarnell** [comment]
@kgeo note that I haven't written off XP just yet, though there are limits to what I can do given I don't have an XP machine any more, and mongo and fibers no longer support it.

Please take a look at issue: https://github.com/sdarnell/meteor/issues/22

If you replace the fibers.node binary I suspect it should work. My guess is that there is a missing runtime library.

**Comment by kgeo** [comment]
Thanks so much @sdarnell !!! That actually worked! 

I know I should get rid of this XP thing, but it's not that easy...

**Comment by sdarnell** [comment]
Glad I could help.
