### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by peterennis** [sdarnell/meteor-win#66]
Latest successful build result log here:
https://github.com/peterennis/meteor/commit/3778656049866f7de355203dffc12d72532fdf8f

It now appropriately shows built from checkout:

```
c:\ae\meteor>scripts\windows\build.bat >> build.log
The system cannot find the file specified.

c:\ae\meteor>meteor --version
Unreleased (running from a checkout)

c:\ae\meteor>.\meteor search sacha
Refreshing package metadata. This may take a moment.
Found the following packages:
sacha:juice  Juice wrapper package
sacha:spin   Simple spinner package for Meteor

To get more information on a specific item, use meteor show.

c:\ae\meteor>
```

I do not see where "The system cannot find the file specified" output message comes from.
Any ideas or should I just debug? There does not appear to be any impact on the build process.

**Comment by sdarnell** [comment]
If you'd not redirected the output of build.bat (or also redirected stderr), it would have been a bit more obvious. I had deliberately enabled 'echo on' to see which command has problems.
Anyway, I have removed the line which was the issue (benign).
