### ISSUE TITLE
Websocket error on console

### ISSUE THREAD

**Issue by serkandurusoy** [sdarnell/meteor-win#9]
I am on Windows 7 64-bit

On my browser console (chrome latest) I get the following:

WebSocket connection to 'ws://localhost:3000/sockjs/509/cdn9f0lp/websocket' failed: WebSocket is closed before the connection is established. 

If I deploy the app on meteor.com, that error disappears.

I tried running meteor from both cmd and cmd run as administrator but that did not make a difference

**Comment by sdarnell** [comment]
Could your firewall be the problem?
I use Chrome on Win7 and don't see this error, so it's a bit tricky for me to investigate.
Do you see the same error with the examples, e.g. todos, leaderboard etc.
If not, can you provide an app or suggest detailed repro steps?
I assume you're using a recent 0.6.3+ version.

**Comment by serkandurusoy** [comment]
Yes, this (windows firewall) was exactly the problem, thank you. Although the node process got prompted by the o/s and an entry was created, adding the mongod process as well as meteor ports exclusively solved the problem.

You might want to consider adding firewall exceptions during installation.

Thank you for your very prompt response.

**Comment by serkandurusoy** [comment]
Hi, I think I was too eager to mark this resolved. I don't know what happened but the same error started appearing again.

BTW I'm on latest rev4 and tried firewall exceptions, disabling firewall altogether etc.

I still get the websockets error on the console.

I see this error in the example apps as well. But my main test app is the microscope app from discover meteor book. https://github.com/DiscoverMeteor/Microscope

**Comment by sdarnell** [comment]
> You might want to consider adding firewall exceptions during installation.

Configuring firewall exclusions is a bit of a nightmare, and there are numerous firewalls.
I think it is probably best to leave it to the user to configure - it is unfortunate that there isn't a better error message that makes it a bit more obvious.

> I see this error in the example apps as well. But my main test app is the microscope app from discover meteor 

Sorry I do see this error in the Chrome console:

```
WebSocket connection to 'ws://localhost:3000/sockjs/891/l1pvtt4m/websocket' failed: WebSocket is closed before the connection is established.
http://localhost:3000/packages/livedata/sockjs-0.3.4.js?230e49f4bc61c91d07c27132d4131ab8bbabcfaf
WebSocketTransport.doCleanup sockjs-0.3.4.js:1261
SockJS._didClose sockjs-0.3.4.js:1061
(anonymous function) sockjs-0.3.4.js:1156
```

But I think this error is normal fallback behaviour, and I can see my app dropping back to PUT requests and long polling. So apps should still work fine.

This is not ideal of course, so I'll have to dig into the sockjs code to see why websockets aren't working on Windows.

**Comment by serkandurusoy** [comment]
I tried other approach to test the issue.
- I tested the same app deployed on meteor.com and there is no problem accessing it from windows or linux
- I fired up a linux box (virtualbox nat networking with forwarded ports) and ran the app from within linux. chrome in linux has no problem, but chrome in windows reports the error 
- I set the linux box to bridge networking so it has its own IP address, and the problem disappears
- I accessed my local (windows) meteor from another windows client in the form of http://ipaddress:3000 and websockets worked just fine
- I accessed my local windows meteor using 127.0.0.1:3000 and also ipaddress:3000 and there was no problem

I can now somewhat safely deduce that accessing "localhost" and looking for websockets in windows seems to present a problem.

It might be a loopback address problem or a problem related to meteor, I cannot say for sure. But what I now do to avoid the error and make use of websockets is use 127.0.0.1:3000 instead of localhost:3000

I am not marking the issue resolved, as I believe it should be your call now :)

**Comment by sdarnell** [comment]
Thanks for the info - that's really helpful. It seems to suggest that the problem is either a Chrome issue or something in SockJS that reacts badly with Chrome.

For me, 127.0.0.1 worked without error, but localhost or the machine name falls back.

**Comment by serkandurusoy** [comment]
would you perhaps like to escalate this issue to the core meteor team and let them decide on the proper course of action?

**Comment by sdarnell** [comment]
I did some more investigation and think the root cause is IPv6, and localhost (at least on Windows) defaulting to the IPv6 address. But the http-proxy inside meteor is configured to explicitly listen on the IPv4 127.0.0.1

**Comment by serkandurusoy** [comment]
I have already tried it; explicitely tried editing hosts file to point to ipv4 and also disabled ipv6 and it still yielded the error so I doubt it is an ip layer issue

Sent from my iPhone

On Jun 11, 2013, at 2:13, Stephen Darnell notifications@github.com wrote:

I did some more investigation and think the root cause is IPv6, and localhost (at least on Windows) defaulting to the IPv6 address. But the http-proxy inside meteor is configured to explicitly listen on the IPv4 127.0.0.1

**Comment by sdarnell** [comment]
Hmm, I managed to get rid of the warning by adding a `127.0.0.1 localhost` line to my hosts file.
Similarly changing the address that the proxy listens on to ::1 fixed things.

However, since trying a few things this morning I am now getting mixed results (::1 in the http-proxy no longer works) and  adding a hosts entry for 127.0.0.1 no longer works.... sigh.
So I'm a bit confused at the moment. :(

**Comment by sdarnell** [comment]
Further testing with reboots and shutting programs done etc, I get the following:
- With the `127.0.0.1 localhost` chrome doesn't produce the error - at least, it works > 95% of the time
- More significantly, the without any changes, I find that refreshing chrome (with no other changes) it works about 5% of the time.

So I am now tending towards it being something else - e.g. more timing related, and presumably the explicit hosts entry changes the timing or something.

Before spending any more time on this I plan to upgrade to 0.6.4 (with a newer http-proxy).

**Comment by serkandurusoy** [comment]
Unfrtunately, that's also what I have encountered, perhaps a little more consistent towards error

Do you think you can upgrade to the newest release to see if there is any improvement?

Sent from my iPhone

On Jun 11, 2013, at 11:39, Stephen Darnell notifications@github.com wrote:

Hmm, I managed to get rid of the warning by adding a 127.0.0.1 localhost line to my hosts file.
Similarly changing the address that the proxy listens on to ::1 fixed things.

However, since trying a few things this morning I am now getting mixed results (::1 in the http-proxy no longer works) and adding a hosts entry for 127.0.0.1 no longer works.... sigh.
So I'm a bit confused at the moment. :(

**Comment by serkandurusoy** [comment]
I also observed that to be able to consistently see the error, the page has to be hard reloaded with ctrl+R otherwise error may disappera, but ai think that's due to meteor giving up on websockets and falling back on sockjs

I'm also eager to see 0.6.4 results but the I think I saw the release notes mentioning we are not perfectly safe until nodejs releases a new upgraded version

Sent from my iPhone

On Jun 11, 2013, at 12:35, Stephen Darnell notifications@github.com wrote:

Further testing with reboots and shutting programs done etc, I get the following:

With the 127.0.0.1 localhost chrome doesn't produce the error - at least, it works > 95% of the time
More significantly, the without any changes, I find that refreshing chrome (with no other changes) it works about 5% of the time.
So I am now tending towards it being something else - e.g. more timing related, and presumably the explicit hosts entry changes the timing or something.

Before spending any more time on this I plan to upgrade to 0.6.4 (with a newer http-proxy).

**Comment by sdarnell** [comment]
Sadly 0.6.4 doesn't seem to change the situation significantly. Most of the time websockets don't work, but occasionally they do - with only refreshing the page in between.

**Comment by sdarnell** [comment]
I've been doing some more investigation and debugging of SockJS. What is happening is that SockJS sets a timeout for each type of protocol, and switches to the next if the timeout expires.
Websockets is the first protocol in the list, and the error is the result of the timeout.
SockJS uses an estimate of the round trip time multiplied by a fixed constant to set the timeout, and on my Windows box at least, this is too agressive and exceeds the timeout most of the time.

For me the RTO value in SockJS is around 561ms, resulting in a timeout of 1122ms.
Yet, the time to connect a websocket seems to be about a second and a half - and therefore fails.

I have hacked things to double the timeout and I've not seen a failure.
So possibly SockJS is being too agressive, or the server side of Meteor is being too slow, and I'm not sure which, though 1.5s to establish a local connection of any sort seems pretty darn slow to me.

**Comment by sdarnell** [comment]
Here are some runs for reference with timing (ms):
   RTO: 582, 546, 561, 570, 573, 522, 230, 272, 546, 
   Connection: 1029, 1018, 1048, 1024, 1020, 1013, TO, TO, 1023  (TO = Timeout even with double)

So at least for these runs the connection establishment time was stable at about a second (still pretty slow?).

**Comment by serkandurusoy** [comment]
Very interesting findings. What puzzles me is that the problem is repeated only when http://localhost is used but not when http://127.0.0.1 is used. On the o/s level, resolution of localhost to 127.0.0.1 is almost negligible and in fact, it is done before meteor is hit. So your results - while very interesting and seem-to-be-conclusive - are all the more puzzling to me.

**Comment by sdarnell** [comment]
Yeah, I'm pretty confused at the minute. When I recorded the times with 127.0.0.1 the websocket connection completed in 20ms ... That's more like it.

I also found a simple websocket test site and was able to establish a connection with that server inc DNS lookup in 250-350ms, which seems OK albeit a little slow. Still digging...

**Comment by sdarnell** [comment]
OK, this is an update on the latest investigation into this issue - at this stage, mostly just data but it is narrowing down where the cause of the problem is somewhere in the chrome websocket implementation.

The timing I added was a simple hack to the sockjs code where the WebSocket is created. I added other traces, but these are the interesting ones:

``` javascript
     var Constructor = _window.WebSocket || _window.MozWebSocket;

     that.ws = new Constructor(that.url);
+    console.log("XX Constructor "+(new Date()).toISOString(), this.ws);
+    that.ws.onopen = function() {
+    console.log("XX onopen "+(new Date()).toISOString(), this.ws);
+    };
     that.ws.onmessage = function(e) {
         that.ri._didMessage(e.data);
     };

```

Timings, completely outside of meteor I used a tweaked version of the example code at: http://www.websocket.org/echo.html and the time to connect a websocket to www.websocket.org is about 250-350ms.

If I deploy a todos example to meteor.com with the tracing above, I get the following (approx 480ms):

```
Kickoff at 2013-06-19T08:06:31.159Z
XX Try next protocol 2013-06-19T08:06:32.097Z
XX Timeout 4956   2013-06-19T08:06:32.098Z
Opening transport: websocket  url:https://ddp--8640-websocket_test.meteor.com/sockjs/528/pi35onio  RTO:2478
XX Constructor 2013-06-19T08:06:32.100Z WebSocket {binaryType: "blob", extensions: "", protocol: "", onclose: null, onerror: null…}
XX Transport 2013-06-19T08:06:32.104Z E.websocket {ri: E, url: "wss://ddp--8640-websocket_test.meteor.com/sockjs/528/pi35onio/websocket", ws: WebSocket, unload_ref: "r4mxbxup", doSend: function…}
XX onopen 2013-06-19T08:06:32.588Z undefined
XX readyState=OPEN 2013-06-19T08:06:32.589Z
_connected at 2013-06-19T08:06:32.592Z 

Time to Constructor-onopen = 488ms
```

but note that the timeout sockjs uses is about 5 seconds, so this usually succeed.

Exactly the same app served by the development server (on Win7 x64) using localhost:3000  (approx 1000ms):

```
Kickoff at 2013-06-19T08:13:52.662Z
XX Try next protocol 2013-06-19T08:13:52.876Z
XX Timeout 532   2013-06-19T08:13:52.876Z
Opening transport: websocket  url:http://localhost:3000/sockjs/340/7s0gfpj8  RTO:266
XX Constructor 2013-06-19T08:13:52.877Z WebSocket {binaryType: "blob", extensions: "", protocol: "", onclose: null, onerror: null…}
XX Transport 2013-06-19T08:13:52.879Z SockJS.websocket {ri: SockJS, url: "ws://localhost:3000/sockjs/340/7s0gfpj8/websocket", ws: WebSocket, unload_ref: "0w5mc_9x", doSend: function…}
XX onopen 2013-06-19T08:13:53.886Z undefined
XX readyState=OPEN 2013-06-19T08:13:53.887Z
_connected at 2013-06-19T08:13:53.888Z

Time to Constructor-onopen = 1009ms
```

This time I repeated the test with the URL as 127.0.0.1 (approx 10-20ms):

```
Kickoff at 2013-06-19T08:17:00.807Z
XX Try next protocol 2013-06-19T08:17:01.040Z
XX Timeout 1002   2013-06-19T08:17:01.040Z
Opening transport: websocket  url:http://127.0.0.1:3000/sockjs/521/gf0ykck7  RTO:501
XX Constructor 2013-06-19T08:17:01.042Z WebSocket {binaryType: "blob", extensions: "", protocol: "", onclose: null, onerror: null…}
XX Transport 2013-06-19T08:17:01.043Z SockJS.websocket {ri: SockJS, url: "ws://127.0.0.1:3000/sockjs/521/gf0ykck7/websocket", ws: WebSocket, unload_ref: "7be_axku", doSend: function…}
XX onopen 2013-06-19T08:17:01.054Z undefined
XX readyState=OPEN 2013-06-19T08:17:01.055Z
_connected at 2013-06-19T08:17:01.056Z

Time to Constructor-onopen = 12ms
```

I repeated the same test with the hosts file having an explicit `127.0.0.1 localhost` and the time was comparable to specifying 127.0.0.1 explicitly in the URL.

Using PowerShell I can time the DNS lookup time accurately:

```
PS C:\meteor\todos> [System.Net.Dns]::GetHostEntry("localhost")

HostName                   Aliases                    AddressList
--------                   -------                    -----------
sammy                      {}                         {::1, 127.0.0.1}
```

Wrapping that in measure-command and it takes between 2 and 4 milliseconds.

The next step was to attach procmon and see what is going on inside Chrome when the delay occurs. Here is the corresponding traces so that the times can be compared to the ones lower down:

```
Kickoff at 2013-06-19T08:38:23.945Z
XX Try next protocol 2013-06-19T08:38:24.185Z
XX Timeout 456   2013-06-19T08:38:24.185Z
Opening transport: websocket  url:http://localhost:3000/sockjs/354/1oef1tou  RTO:228
XX Constructor 2013-06-19T08:38:24.187Z WebSocket {binaryType: "blob", extensions: "", protocol: "", onclose: null, onerror: null…}
XX Transport 2013-06-19T08:38:24.189Z SockJS.websocket {ri: SockJS, url: "ws://localhost:3000/sockjs/354/1oef1tou/websocket", ws: WebSocket, unload_ref: "h8rckpbs", doSend: function…}
XX onopen 2013-06-19T08:38:25.201Z undefined
XX readyState=OPEN 2013-06-19T08:38:25.202Z
_connected at 2013-06-19T08:38:25.203Z 
```

The procmon traces showed nothing significant going on between 24.187 and 25.201, and here is the network activity entries that show it didn't try to connect until 25.192:

```
09:38:23.6471117    chrome.exe  2648    0   TCP Receive sammy:51623 -> sammy:3000   SUCCESS Length: 908, seqnum: 0, connid: 0
09:38:23.6471277    chrome.exe  2648    0   TCP Receive sammy:51623 -> sammy:3000   SUCCESS Length: 3205, seqnum: 0, connid: 0
09:38:23.6472887    chrome.exe  2648    0   TCP Receive sammy:51623 -> sammy:3000   SUCCESS Length: 2, seqnum: 0, connid: 0
09:38:23.6474529    chrome.exe  2648    0   TCP Receive sammy:51623 -> sammy:3000   SUCCESS Length: 5, seqnum: 0, connid: 0
09:38:23.8168443    chrome.exe  2648    0   TCP Reconnect   sammy:51617 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:23.8248410    chrome.exe  2648    0   TCP Reconnect   sammy:51620 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:23.8248422    chrome.exe  2648    0   TCP Reconnect   sammy:51619 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:23.8268409    chrome.exe  2648    0   TCP Reconnect   sammy:51621 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:23.8348427    chrome.exe  2648    0   TCP Reconnect   sammy:51622 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:24.1701515    chrome.exe  2648    0   TCP Send    sammy:51623 -> sammy:3000   SUCCESS Length: 292, startime: 3370479, endtime: 3370479, seqnum: 0, connid: 0
09:38:24.1707339    chrome.exe  2648    0   TCP Send    sammy:51624 -> sammy:3000   SUCCESS Length: 325, startime: 3370479, endtime: 3370479, seqnum: 0, connid: 0
09:38:24.1761187    chrome.exe  2648    0   TCP Receive sammy:51624 -> sammy:3000   SUCCESS Length: 294, seqnum: 0, connid: 0
09:38:24.1763342    chrome.exe  2648    0   TCP Receive sammy:51624 -> sammy:3000   SUCCESS Length: 79, seqnum: 0, connid: 0
09:38:24.1764727    chrome.exe  2648    0   TCP Receive sammy:51624 -> sammy:3000   SUCCESS Length: 2, seqnum: 0, connid: 0
09:38:24.1778672    chrome.exe  2648    0   TCP Receive sammy:51624 -> sammy:3000   SUCCESS Length: 5, seqnum: 0, connid: 0
09:38:24.1789852    chrome.exe  2648    0   TCP Receive sammy:51623 -> sammy:3000   SUCCESS Length: 143, seqnum: 0, connid: 0
09:38:24.3208593    chrome.exe  2648    0   TCP Reconnect   sammy:51619 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:24.3228535    chrome.exe  2648    0   TCP Reconnect   sammy:51620 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:24.3348533    chrome.exe  2648    0   TCP Reconnect   sammy:51618 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:24.3348700    chrome.exe  2648    0   TCP Reconnect   sammy:51622 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:24.4118644    chrome.exe  2648    0   TCP Reconnect   sammy:51621 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:24.4118843    chrome.exe  2648    0   TCP Reconnect   sammy:51617 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:24.6918545    chrome.exe  2648    0   TCP Reconnect   sammy:51632 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:25.1918753    chrome.exe  2648    0   TCP Reconnect   sammy:51632 -> sammy:3000   SUCCESS Length: 0, seqnum: 0, connid: 0
09:38:25.1923923    chrome.exe  2648    0   TCP Connect sammy:51633 -> sammy:3000   SUCCESS Length: 0, mss: 1460, sackopt: 1, tsopt: 0, wsopt: 1, rcvwin: 8192, rcvwinscale: 8, sndwinscale: 8, seqnum: 0, connid: 0
09:38:25.1938426    chrome.exe  2648    0   TCP Send    sammy:51633 -> sammy:3000   SUCCESS Length: 429, startime: 3370490, endtime: 3370490, seqnum: 0, connid: 0
09:38:25.2011279    chrome.exe  2648    0   TCP Receive sammy:51633 -> sammy:3000   SUCCESS Length: 125, seqnum: 0, connid: 0
09:38:25.2012690    chrome.exe  2648    0   TCP Receive sammy:51633 -> sammy:3000   SUCCESS Length: 51, seqnum: 0, connid: 0
09:38:25.2066628    chrome.exe  2648    0   TCP Send    sammy:51633 -> sammy:3000   SUCCESS Length: 75, startime: 3370490, endtime: 3370490, seqnum: 0, connid: 0
```

So I am left thinking that when Chrome sees the IPv6 loopback address it actively has a sleep - possibly for security reasons (see http://stackoverflow.com/questions/12665887/chrome-websocket-connection-delay) but given the inconsistency with 127.0.0.1 this seems unlikely.

**Comment by sdarnell** [comment]
I raised a Chrome bug report.

The chrome/chromium code for websockets does have logic for throttling connections to the same address (and the websockets spec requires this). See https://code.google.com/p/chromium/codesearch#chromium/src/net/websockets/websocket_throttle.cc

However, I don't think it should be kicking in as the two addresses (IPV6 ::1 and IPV4 127.0.0.1) should be treated as separate addresses, and I also can't see why the code would delay for a second. There doesn't seem to be a time limit, or sleep etc. The code seems to release pending websocket jobs immediately - though I'm clearly not familiar with this code. I'm also not sure which version of the code is in the latest chrome.

**Comment by serkandurusoy** [comment]
Great job pinning this down. On the other hand, I am inclined to think that although raising a Chrome bug report is a good idea, perhaps an "enhancement request" should be created on Meteor part and handling this "race condition".

**Comment by sdarnell** [comment]
Raised a chromium issue directly: https://code.google.com/p/chromium/issues/detail?id=272360

**Comment by sdarnell** [comment]
This now seems to be working well. I've also raised a pull request for core meteor (https://github.com/meteor/meteor/pull/1406), but given the discussions about switching to a different http proxy, I suspect it will need re-writing before it gets into core.
